### ISSUE TITLE
How to draw a texture over the Square of HelloOpenGLES20 ?

### ISSUE THREAD

**Issue by RegisAG** [JimSeker/opengl#2]
I tested the OpenGL ES 2.0 demo project here : https://github.com/JimSeker/opengl/tree/master/HelloOpenGLES20

It draws a triangle and a square with a uniform color. Great!

Class to draw the Square : https://github.com/JimSeker/opengl/blob/master/HelloOpenGLES20/app/src/main/java/com/example/android/opengl/Square.java

Now, I would like a modified Square.java class in order to have a rectangle (size 1005x20) instead of a square. And I want to cover this rectangle with a repetitive texture (size 10x10) over its height and width (100.5 textures over the length and 2 over the width).

Anybody could tell me how to modify the code ? And the modified vertex and fragment shaders?

Thanks.

**Comment by JimSeker** [comment]
These are only intended to get you started.  Once you got the basics of android and open GL, you need openGL ES help.  There are number of very good tutorials and books.   maybe more then you need, but http://www.learnopengles.com/android-lesson-one-getting-started/  and look at lesson four for textures.
